- hosts: devwebservers
  vars:
    empty_dirs:
      - "/var/cdn/dev/public/"
      - "/var/www/dev.diluv.io/"
      - "/var/www/dev.diluv.io/public"
  tasks:
    - file: state=absent path={{ item }}
      with_items: empty_dirs

    - name: copy index to nginx
      synchronize: src=dist/index.html dest=/var/www/dev.diluv.io/index.html

    - name: copy main bundle to nginx
      synchronize: src={{ item }} dest=/var/www/dev.diluv.io/public/
      with_fileglob:
        - dist/main-bundle*.js

    - name: copy public folder to nginx
      synchronize: src=public/ dest=/var/www/dev.diluv.io/public/

    - name: copy public folder to cdn
      synchronize: src=public/ dest=/var/cdn/dev/public/

    - name: copy main bundle to cdn
      synchronize: src={{ item }} dest=/var/cdn/dev/public/
      with_fileglob:
        - dist/main-bundle*.js

