- hosts: webservers
  vars:
    empty_dirs:
      - "/var/cdn/dev/public/"
      - "/var/www/dev.diluv.io/"
      - "/var/www/dev.diluv.io/public"
  tasks:
    - file: state=absent path={{ item }}
      with_items: empty_dirs

    - name: copy index to nginx
      copy: src=dist/index.html dest=/var/www/dev.diluv.io/index.html

    - shell: ls -d dist/main-bundle*.js
      register: dir_name

    - copy: src=dir_name.stdout dest=/var/www/dev.diluv.io/public

    - name: copy public folder to nginx
      copy: src=public/ dest=/var/www/dev.diluv.io/public

    - copy: src=dir_name.stdout dest=/var/cdn/dev/public/

    - name: copy public folder to cdn
      copy: src=public/ dest=/var/cdn/dev/public/

