- hosts: apiservers
  tasks:
    - name: copy index.html to nginx
      copy: src=dist/index.html dest=/var/www/dev.diluv.io/

    - name: copy main-bundle.js cdn
      copy: src=dist/main-bundle.js dest=/var/cdn/dev/

    - name: copy public folder to nginx
      copy: src=public/ dest=/var/cdn/dev/