- hosts: apiservers
  tasks:
    empty_dirs:
      - "/var/cdn/dev/public/"
      - "/var/www/dev.diluv.io/"

    - file: state=absent path={{ item.path }}
      with_items:
        - "{{ files }}"

    - name: copy dist
      copy: src=dist/ dest=/var/www/dev.diluv.io/

    - name: copy public folder to nginx
      copy: src=public/ dest=/var/cdn/dev/public