- hosts: webservers
  vars:
    empty_dirs:
      - "/var/cdn/dev/public/"
      - "/var/www/dev.diluv.io/"
      - "/var/www/dev.diluv.io/public"
  tasks:
    - file: state=absent path={{ item }}
      with_items: empty_dirs

    - name: copy dist to nginx
      copy: src=dist/ dest=/var/www/dev.diluv.io/

    - name: copy public folder to nginx
      copy: src=public/ dest=/var/www/dev.diluv.io/public

    - name: copy main bundle to cdn
      copy: src=dist/main-bundle.js dest=/var/cdn/dev/public/

    - name: copy public folder to cdn
      copy: src=public/ dest=/var/cdn/dev/public/

